# Generated by Django 2.2.2 on 2019-06-27 20:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import galaxy_common.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galaxy', '0002_namespace_provider_providernamespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='owners',
            field=models.ManyToManyField(related_name='namespaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferences', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('collections_followed', models.ManyToManyField(blank=True, to='galaxy.Collection')),
                ('namespaces_followed', models.ManyToManyField(blank=True, to='galaxy.Namespace')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, galaxy_common.models.mixins.DirtyMixin),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=128)),
                ('seen', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galaxy.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, galaxy_common.models.mixins.DirtyMixin),
        ),
        migrations.CreateModel(
            name='UserAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=30, unique=True)),
                ('alias_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserAliases',
            },
        ),
    ]
